export const products = [
  {
    id: 1,
    title: "BOTITAS JORDAN AIR 5 RETRO",
    marca: "Jordan",
    price: 87999,
    stock: 2,
    description:
      "UN ÍCONO EN LAS CALLES. Obtén tu parte de la historia y herencia de Jordan con el Air Jordan 5 Retro. Inspirado en el clásico calzado de juego de 1990, cuenta con todos los detalles icónicos, como el cuello desigual, los cordones con bloqueo regulable y las líneas de diseño inspiradas en los aviones de combate.",
    category: "Urbanas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688344680/Proyecto%20React%20Js/Zapatillas%20Jordan/BOTITAS%20JORDAN%20AIR%205%20RETRO%20BLANCO.jpg",
  },
  {
    id: 2,
    title: "BOTITAS JORDAN AIR 1 MID TRUE BLUE",
    marca: "Jordan",
    price: 72999,
    stock: 2,
    description:
      "ESTILO TRADICIONAL Y COMODIDAD PREMIUM DENTRO Y FUERA DE LA CANCHA. El calzado Air Jordan 1 Mid aporta estilo en toda la cancha y comodidad premium a un look icónico. La unidad Air-Sole amortigua el partido en las canchas, y el cuello acolchado ofrece una mayor sujeción.",
    category: "Urbanas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688344512/Proyecto%20React%20Js/Zapatillas%20Jordan/BOTITAS%20JORDAN%20AIR%201%20MID%20TRUE%20BLUE.jpg",
  },
  {
    id: 3,
    title: "ZAPATILLAS JORDAN AIR 1 LOW",
    marca: "Jordan",
    price: 66999,
    stock: 8,
    description:
      "SIEMPRE RENOVADO. Inspirado en el original que se lanzó en 1985, el Air Jordan 1 Low ofrece un estilo clásico impecable que se resulta familiar, pero renovado. Con un diseño icónico que combina perfectamente con cualquier ajuste, este calzado garantiza que siempre estará a la moda.",
    category: "Urbanas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688344659/Proyecto%20React%20Js/Zapatillas%20Jordan/ZAPATILLAS%20JORDAN%20AIR%201%20LOW.jpg",
  },
  {
    id: 4,
    title: "BOTITAS JORDAN MAX AURA 4",
    marca: "Jordan",
    price: 71999,
    stock: 2,
    description:
      "La amortiguación ligera que se encuentra en este calzado de básquetbol de última generación se inspira en sus predecesores. Toma vuelo en la cancha con un estilo atemporal y soporte en el talón que se siente como una nube.",
    category: "Urbanas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688344456/Proyecto%20React%20Js/Zapatillas%20Jordan/BOTITAS%20JORDAN%20MAX%20AURA%204.jpg",
  },
  {
    id: 5,
    title: "ZAPATILLAS ADIDAS ORIGINALS SUPERSTAR",
    marca: "Adidas",
    price: 71999,
    stock: 6,
    description:
      "Las Zapatillas Urbanas adidas Superstar Hombre no necesitan mucha presentación. Su historia hizo que dejen de ser un calzado para ser un ícono de la moda. Nacidas en los 70's para el básquet, fueron recorriendo el mundo urbano de la mano del skateboarding y principalmente el hip-hop. Estilo de sobra con el detalle de las tres tiras (three-stripes) típicas de la marca que agregan detalle de color y elegancia y su característica puntera de caucho.",
    category: "Urbanas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688345446/Proyecto%20React%20Js/Adidas%20Originals/ZAPATILLAS%20ADIDAS%20ORIGINALS%20SUPERSTAR%20GREY.jpg",
  },
  {
    id: 6,
    title: "ZAPATILLAS ADIDAS ORIGINALS FORUM LOW BLANCO",
    marca: "Adidas",
    price: 44499,
    stock: 2,
    description:
      "Con un estilo urbano y para recorrer diferentes lugares, las zapatillas Adidas Forum Low están confeccionadas en cuero sintético y suela de goma para un mayor agarre sobre la superficie. Su ajuste con cordones y velcro le dan un toque retro, inspirado en 1984 cuando las Forum salieron por primera vez a conquistar canchas de básquet y el mundo del hip-hop. Usalas todo el día, las calles de tu ciudad las estaban esperando.",
    category: "Urbanas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688345308/Proyecto%20React%20Js/Adidas%20Originals/ZAPATILLAS%20ADIDAS%20ORIGINALS%20FORUM%20LOW%20BLANCO.jpg",
  },
  {
    id: 7,
    title: "ZAPATILLAS ADIDAS ORIGINALS NMD_R1",
    marca: "Adidas",
    price: 52799,
    stock: 2,
    description:
      "¿Querés sentirte cómodo sin perder el estilo? Entonces las Zapatillas Urbanas adidas Nmd R1 Hombre son para vos. Su capellada de malla brinda elasticidad y transpirabilidad para que te muevas en cualquier dirección sin interrupciones. Además, su tecnología Boost ayuda a reducir el impacto en cada pisada y al mismo tiempo tomar impulso, manteniendo tu energía mientras realizás cualquier actividad. Sentite seguro gracias a su suela de goma que se adhiere al pavimento para brindarte la mejor experiencia al andar.",
    category: "Urbanas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688345085/Proyecto%20React%20Js/Adidas%20Originals/ZAPATILLAS%20ADIDAS%20ORIGINALS%20NMD_R1.jpg",
  },
  {
    id: 8,
    title: "ZAPATILLAS ADIDAS ORIGINALS SUPERSTAR",
    marca: "Adidas",
    price: 40899,
    stock: 2,
    description:
      "Las Zapatillas Urbanas adidas Superstar Hombre son un ícono de estilo que nunca pasa de moda. Con su clásico diseño de puntera de goma y las famosas tres rayas de Adidas, te brindan un look urbano auténtico y versátil. Su parte superior de cuero suave y su suela de caucho ofrecen comodidad y durabilidad. Lucí un estilo legendario llevando estas zapatillas en tus pies.",
    category: "Urbanas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688345339/Proyecto%20React%20Js/Adidas%20Originals/ZAPATILLAS%20ADIDAS%20ORIGINALS%20SUPERSTAR.jpg",
  },
  {
    id: 9,
    title: "BOTITAS NIKE AIR FORCE 1 HIGHT 07 LV8",
    marca: "Nike",
    price: 68309,
    stock: 2,
    description:
      "ESTILO DE HERENCIA CON FUERZA. El Nike Air Force 1 High '07 es todo lo que ya conoces: revestimientos impecables, acentos audaces y el estilo clásico del básquetbol. El cuello acolchado de corte high con cierre por contacto agrega la comodidad clásica del básquetbol, mientras que la suela de goma te brinda tracción dentro y fuera de la cancha.",
    category: "Urbanas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688345728/Proyecto%20React%20Js/Nike/BOTITAS%20NIKE%20AIR%20FORCE%201%20HIGHT%2007%20LV8.jpg",
  },
  {
    id: 10,
    title: "ZAPATILLAS NIKE AIR FORCE 1 REACT",
    marca: "Nike",
    price: 82999,
    stock: 2,
    description:
      "Únete a la fiesta y celebra 40 años de desafiar los límites del deporte y la moda con el Nike Air Force 1 React. Dando un paso audaz hacia la iconografía del básquetbol, su espuma React suave y, la suela amplificada rinden aportan una nueva comodidad. Los detalles en oro pulido y la marca fresca que combina logotipos de lanzamientos pasados rinden homenaje al estilo audaz fuera de la cancha y rinden homenaje al reinado del AF1.",
    category: "Urbanas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688345673/Proyecto%20React%20Js/Nike/ZAPATILLAS%20NIKE%20AIR%20FORCE%201%20REACT.jpg",
  },
  {
    id: 11,
    title: "BOTITAS NIKE LUNAR FORCE 1 DUCKBOOT",
    marca: "Nike",
    price: 107999,
    stock: 2,
    description:
      "Una leyenda para usar durante los días más fríos, las Zapatillas Urbanas Nike Lunar Force 1 Hombre son el calzado que no pueden falarte en tu armario. Cuentan con un herraje metálico en la lengüeta que brinda resistencia tipo bota de montaña y un diseño de punta decorada con tachuelas de estrellas que brinda un look premium de máxima calidad. Además, la unidad Air brinda mayor amortiguación para que tus pisadas se vuelvan cómodas y livianas. Definitivamente son las mejores compañeras para afrontar las bajas temperaturas.",
    category: "Urbanas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688345640/Proyecto%20React%20Js/Nike/BOTITAS%20NIKE%20LUNAR%20FORCE%201%20DUCKBOOT.jpg",
  },
  {
    id: 12,
    title: "BOTITAS NIKE DUNK HI RETRO",
    marca: "Nike",
    price: 69999,
    stock: 2,
    description:
      "LLEGA ALTO CON UNA LEYENDA DEL BaSQUETBOL. Lleva tu dia a lo mas alto con esta leyenda del Basquetbol. El Nike Dunk regresa con durabilidad y soporte para cada jugador. Con un diseño retro y en tallas para niños, esta es una facil elección para incluir en tu colección de calzado deportivo.",
    category: "Urbanas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688345656/Proyecto%20React%20Js/Nike/BOTITAS%20NIKE%20DUNK%20HI%20RETRO.jpg",
  },
  {
    id: 13,
    title: "Adidas Ultraboost 22",
    marca: "Adidas",
    price: 62399,
    stock: 2,
    description:
      "Las Zapatillas adidas Ultraboost 22 son una mejora de su predecesor, con un calce perfeccionado y una suela que optimiza tu tracción día a día. El calce es ideal para los corredores más exigentes, con un tejido PRIMEKNIT en la capellada que se ajusta mejor a ellos para evitar resbalones y accidentes. La mediasuela BOOST mejora la amortiguación y su sistema Linear Energy Push garantiza el retorno de energía que necesitas para sumar kilómetros en cada salida.",
    category: "Deportivas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688396095/Proyecto%20React%20Js/Adidas%20Deportivas/Zapatillas%20adidas%20Ultraboost%2022%20Black.jpg",
  },
  {
    id: 14,
    title: "Adidas Ultraboost Light Unisex",
    marca: "Adidas",
    price: 99999,
    stock: 2,
    description:
      "Agregá una experiencia de energía a tus carreras con las Zapatillas Running adidas Ultraboost Light Unisex. Un calzado hecho para darte comodidad, amortiguación y retorno de energía gracias a su mediasuela BOOST y una confección en mesh que le añade libertad a tus pies. Además, están hechas con contenido reciclado para hacerte sentir muy bien al llevarlas puestas.",
    category: "Deportivas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688396079/Proyecto%20React%20Js/Adidas%20Deportivas/Zapatillas%20Running%20adidas%20Ultraboost%20Light%20Unisex.jpg",
  },
  {
    id: 15,
    title: "Adidas Ultraboost 22",
    marca: "Adidas",
    price: 62399,
    stock: 2,
    description:
      "Las Zapatillas adidas Ultraboost 22 son una mejora de su predecesor, con un calce perfeccionado y una suela que optimiza tu tracción día a día. El calce es ideal para los corredores más exigentes, con un tejido PRIMEKNIT en la capellada que se ajusta mejor a ellos para evitar resbalones y accidentes. La mediasuela BOOST mejora la amortiguación y su sistema Linear Energy Push garantiza el retorno de energía que necesitas para sumar kilómetros en cada salida.",
    category: "Deportivas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688396058/Proyecto%20React%20Js/Adidas%20Deportivas/Zapatillas%20adidas%20Ultraboost%2022.jpg",
  },
  {
    id: 16,
    title: "Adidas 4DFWD Pulse Hombre",
    marca: "Adidas",
    price: 60099,
    stock: 2,
    description:
      "Las Zapatillas adidas 4d Fwd Pulse es la clave para tus momentos de running. Cuenta con un refuerzo en el talón tridimensional a partir de resina líquida, luz y oxígeno para lograr un mejor control de impactos y contribuir a un despegue e impulsos muchos más rápidos. La malla de su parte superior te otorga ventilación y a la vez, permite mover tus pies con mayor libertad. Además, están hechas con al menos un 50% de contenido reciclado, para que además de ocuparte de tu salud, te comprometas aún más con el planeta. No te las vas a querer sacar.",
    category: "Deportivas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688396034/Proyecto%20React%20Js/Adidas%20Deportivas/Zapatillas%20Running%20adidas%204DFWD%20Pulse%20Hombre.jpg",
  },
  {
    id: 17,
    title: "Asics Gel-nimbus 25",
    marca: "Asics",
    price: 71299,
    stock: 2,
    description:
      "Poné el cronómetro y empezá a medir tu carrera con las Zapatillas Asics Gel-nimbus 25. Un calzado hecho especialmente para darte rendimiento, comodidad y soporte durante todo el momento que las lleves puestas. Con una construcción en mesh de calidad para usar por muchos años y una suela de goma elevada que mejora tu postura. La tecnología FF Blast en el antepié te hace sentir como si estuvieras pisando el mismo aire. El diseño de este calzado crea un outfit deportivo ideal para combinar con tu look deportivo.",
    category: "Deportivas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688396523/Proyecto%20React%20Js/Asics%20Deportivas/Zapatillas%20Asics%20Gel-nimbus%2025.jpg",
  },
  {
    id: 18,
    title: "Asics Gel-nimbus 24 Standar",
    marca: "Asics",
    price: 58989,
    stock: 2,
    description:
      "Enciende el GPS y comieza a recrorrer la ciudad con las Zapatillas Asics Gel-nimbus 24 Standar. Super comodas y hechas especialmente para armotiguar el impacto sobre suelo",
    category: "Deportivas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688396541/Proyecto%20React%20Js/Asics%20Deportivas/Zapatillas%20Asics%20Gel-nimbus%2024%20Standar.jpg",
  },
  {
    id: 19,
    title: "Asics Kayano 29 Hombre",
    marca: "Asics",
    price: 64799,
    stock: 2,
    description:
      "Sumergite en las pistas con las Zapatillas Running Asics Kayano 29 Hombre. Un calzado con mucha tecnología para tus momentos de corrida, confeccionado en una parte superior de malla que te entrega transpirabilidad y libertad de movimiento. Incorpora una mediasuela con tecnología GEL para absorber impactos y mejorar cada aterrizaje a lo que se suma la tecnología FF BLAST para un rebote sensible. Con este par, sentirás que estás corriendo en el espacio!",
    category: "Deportivas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688396560/Proyecto%20React%20Js/Asics%20Deportivas/Zapatillas%20Running%20Asics%20Kayano%2029%20Hombre.jpg",
  },
  {
    id: 20,
    title: "Asics Gel-cumulus 24 Se Hombre",
    marca: "Asics",
    price: 55369,
    stock: 2,
    description:
      "Empezá la carrera con las Zapatillas Asics Gel-Cumulus 24 Se. Un calzado con rendimiento óptimo, comodidad y tecnología. Hecho de malla para garantizarte libre movimiento y ventilación en todo el tiempo de entrenamiento y con tecnología FlyteFoam que proporciona amortiguación y resistencia a los impactos. La suela de goma te asegura tracción en distintas superficies para que nada te preocupe ni se interponga en el objetivo. Ponételas y alcanzá la meta, o mejor aún, superala!",
    category: "Deportivas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688396584/Proyecto%20React%20Js/Asics%20Deportivas/Zapatillas%20Running%20Asics%20Gel-cumulus%2024%20Se%20Hombre.jpg",
  },
  {
    id: 21,
    title: "Nike Air Zoom Vomero 16 Hombre",
    marca: "Nike",
    price: 84999,
    stock: 2,
    description:
      "Las Zapatillas Running Nike Air Zoom Vomero 16 Hombre son un calzado deportivo diseñado para ofrecer una gran comodidad y rendimiento en carrera. Confeccionadas con una parte superior de malla transpirable y una suela de goma resistente, ofrecen una gran flexibilidad y tracción en diferentes superficies. La tecnología Zoom Air en la entresuela brinda una amortiguación reactiva y una mayor velocidad. Además, su diseño de corte alto y sus cordones elásticos garantizan un ajuste seguro y único para cada persona. Ideales para corredores que buscan un calzado cómodo, ligero y con excelente amortiguación para sus entrenamientos y competiciones.",
    category: "Deportivas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688396272/Proyecto%20React%20Js/Nike%20Deportivas/Zapatillas%20Running%20Nike%20Air%20Zoom%20Vomero%2016%20Hombre.jpg",
  },
  {
    id: 22,
    title: "Nike React Infinity Run Fk 3 Hombre",
    marca: "Nike",
    price: 83999,
    stock: 2,
    description:
      "Las Zapatillas Running Nike React Infinity Run Fk 3 Hombre son un calzado deportivo diseñado para ofrecer una gran comodidad y rendimiento en carrera.",
    category: "Deportivas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688396295/Proyecto%20React%20Js/Nike%20Deportivas/Zapatillas%20Nike%20React%20Infinity%20Run%20Fk%203%20Hombre.jpg",
  },
  {
    id: 23,
    title: "Nike React Infinity Run Flyknit 3",
    marca: "Nike",
    price: 83999,
    stock: 2,
    description:
      "Las Zapatillas Running Nike React Infinity Run Fk 3 Hombre son un calzado deportivo diseñado para ofrecer una gran comodidad y rendimiento en carrera.",
    category: "Deportivas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688396313/Proyecto%20React%20Js/Nike%20Deportivas/Zapatillas%20Nike%20React%20Infinity%20Run%20Flyknit%203.jpg",
  },
  {
    id: 24,
    title: "Nike Zoom Fly 5 Hombre",
    marca: "Nike",
    price: 94999,
    stock: 2,
    description:
      "Acelera tus pasos con las Zapatillas Running Nike Zoom Fly 5 Hombre. Confeccionadas con materiales sintéticos de alta calidad, con la parte superior de mesh transpirable que mantiene tus pies frescos y una mediasuela con espuma ZoomX que te ayuda a subir el nivel de tu rendimiento. Este calzado te ofrece la comodidad, seguridad y velocidad que necesitas durante todas tus carreras.",
    category: "Deportivas",
    img: "https://res.cloudinary.com/dhdhzwlz9/image/upload/v1688396336/Proyecto%20React%20Js/Nike%20Deportivas/Zapatillas%20Running%20Nike%20Zoom%20Fly%205%20Hombre.jpg",
  },
];
